package sitemap

// roundtrip.go — the round-trip invariant, the heart of "full round-trip
// testing" for sitemaps. xmile's Generate is a faithful inverse of Parse at the
// *canonical infoset*, not byte-for-byte: it always emits the UTF-8 encoding
// declaration and coalesces character data, so a meaningful equality clears the
// encoding declaration and coalesces text runs before comparing — exactly as
// xmile's own generate gate (testing/main.go canonicalXML) does. RoundTrip is
// the check the unit tests and the corpus runner share.

import (
	"google.golang.org/protobuf/proto"

	xmlpb "github.com/accretional/xmile/proto/pb/xml"
	"github.com/accretional/xmile/service"
)

// RoundTrip serializes x with Generate, re-parses the result, and reports
// whether it equals x at the canonical infoset. It returns the regenerated bytes
// too (for diagnostics on failure). A Generate or re-parse error is returned as
// err with ok=false.
func RoundTrip(p *service.Parser, x *xmlpb.Xml) (ok bool, generated []byte, err error) {
	out, err := Generate(x)
	if err != nil {
		return false, nil, err
	}
	x2, err := p.Parse(string(out), false)
	if err != nil {
		return false, out, err
	}
	return proto.Equal(canonicalXML(x), canonicalXML(x2)), out, nil
}

// canonicalXML reduces an Xml AST to the canonical infoset form used for
// round-trip comparison: the encoding declaration is cleared (Generate always
// emits UTF-8) and consecutive character-data items are coalesced with empty
// ones dropped (entity/reference expansion can split one run into several text
// items; the coalesced run is the single character-data item the infoset
// defines). The input is not mutated.
func canonicalXML(x *xmlpb.Xml) *xmlpb.Xml {
	c, _ := proto.Clone(x).(*xmlpb.Xml)
	if d := c.GetXmlDecl(); d != nil {
		d.Encoding = ""
	}
	coalesceText(c.GetRoot())
	return c
}

func coalesceText(t *xmlpb.Tag) {
	if t == nil {
		return
	}
	var out []*xmlpb.ContentItem
	for _, ci := range t.GetContents() {
		if it, ok := ci.GetItem().(*xmlpb.ContentItem_Text); ok {
			if it.Text == "" {
				continue
			}
			if n := len(out); n > 0 {
				if prev, ok := out[n-1].GetItem().(*xmlpb.ContentItem_Text); ok {
					prev.Text += it.Text
					continue
				}
			}
		}
		if child := ci.GetChild(); child != nil {
			coalesceText(child)
		}
		out = append(out, ci)
	}
	t.Contents = out
}
