// sitemap_service.proto — the gRPC surface of cmd/sitemap-svc.
//
// AUTHORED, NOT GENERATED, and the only .proto this repo carries.
//
// proto-sitemap otherwise commits no proto by design: the sitemap *format* is
// data (formats/sitemap.ebnf), compiled to a descriptor at runtime by xmile's
// engine (CLAUDE.md, ADR 0001). That still holds — nothing here describes the
// sitemap format. This file describes the SERVICE: what a caller sends to ask
// for a walk, and what comes back. The typed sitemap AST remains compiled from
// the grammar and never appears on the wire.
//
// Per CLAUDE.md's rule about adding a hand-written proto, ./regen.sh
// regenerates the Go bindings; the generated .pb.go files are committed, so an
// ordinary build needs no protoc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: sitemap_service.proto

package sitemappb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Limits bound a walk. Each field defaults to MaxInt32 server-side, so essentially
// they are unbounded. The walk is limited instead by the request deadline, the 64 MiB
// message cap, and instance memory. Set these explicitly for a walk that always answers, and read
// `truncated` on the response.
type Limits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxUrls       int32                  `protobuf:"varint,1,opt,name=max_urls,json=maxUrls,proto3" json:"max_urls,omitempty"`
	MaxSitemaps   int32                  `protobuf:"varint,2,opt,name=max_sitemaps,json=maxSitemaps,proto3" json:"max_sitemaps,omitempty"`
	MaxDepth      int32                  `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_sitemap_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_sitemap_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_sitemap_service_proto_rawDescGZIP(), []int{0}
}

func (x *Limits) GetMaxUrls() int32 {
	if x != nil {
		return x.MaxUrls
	}
	return 0
}

func (x *Limits) GetMaxSitemaps() int32 {
	if x != nil {
		return x.MaxSitemaps
	}
	return 0
}

func (x *Limits) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type ExpandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The roots of the walk — typically the Sitemap: lines a robots.txt declared.
	// Both <urlset> and <sitemapindex> documents are accepted.
	SitemapUrls []string `protobuf:"bytes,1,rep,name=sitemap_urls,json=sitemapUrls,proto3" json:"sitemap_urls,omitempty"`
	// Identifies the fetcher to the origin. Defaults to the service's own UA.
	UserAgent string `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// When > 0, honoured between successive fetches to the same host
	// (robots.txt Crawl-delay). It serializes that host's fetches.
	CrawlDelaySeconds float64 `protobuf:"fixed64,3,opt,name=crawl_delay_seconds,json=crawlDelaySeconds,proto3" json:"crawl_delay_seconds,omitempty"`
	// Zero fields take the service's default limits.
	Limits        *Limits `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_sitemap_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sitemap_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_sitemap_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExpandRequest) GetSitemapUrls() []string {
	if x != nil {
		return x.SitemapUrls
	}
	return nil
}

func (x *ExpandRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ExpandRequest) GetCrawlDelaySeconds() float64 {
	if x != nil {
		return x.CrawlDelaySeconds
	}
	return 0
}

func (x *ExpandRequest) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

// UrlEntry is one <url> from a <urlset>.
type UrlEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Loc     string                 `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	Lastmod string                 `protobuf:"bytes,2,opt,name=lastmod,proto3" json:"lastmod,omitempty"`
	// The sitemap document this entry came from — useful when a walk spans
	// dozens of child sitemaps.
	SourceSitemap string `protobuf:"bytes,3,opt,name=source_sitemap,json=sourceSitemap,proto3" json:"source_sitemap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlEntry) Reset() {
	*x = UrlEntry{}
	mi := &file_sitemap_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlEntry) ProtoMessage() {}

func (x *UrlEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sitemap_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlEntry.ProtoReflect.Descriptor instead.
func (*UrlEntry) Descriptor() ([]byte, []int) {
	return file_sitemap_service_proto_rawDescGZIP(), []int{2}
}

func (x *UrlEntry) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

func (x *UrlEntry) GetLastmod() string {
	if x != nil {
		return x.Lastmod
	}
	return ""
}

func (x *UrlEntry) GetSourceSitemap() string {
	if x != nil {
		return x.SourceSitemap
	}
	return ""
}

// FetchError records one sitemap that could not be fetched or parsed. A walk
// reports these and continues: a site serving HTML at /sitemap.xml, or one dead
// child of a healthy index, does not fail the whole expansion.
type FetchError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchError) Reset() {
	*x = FetchError{}
	mi := &file_sitemap_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchError) ProtoMessage() {}

func (x *FetchError) ProtoReflect() protoreflect.Message {
	mi := &file_sitemap_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchError.ProtoReflect.Descriptor instead.
func (*FetchError) Descriptor() ([]byte, []int) {
	return file_sitemap_service_proto_rawDescGZIP(), []int{3}
}

func (x *FetchError) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExpandResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Urls             []*UrlEntry            `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	SitemapsFetched  int32                  `protobuf:"varint,2,opt,name=sitemaps_fetched,json=sitemapsFetched,proto3" json:"sitemaps_fetched,omitempty"`
	Truncated        bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	TruncationReason string                 `protobuf:"bytes,4,opt,name=truncation_reason,json=truncationReason,proto3" json:"truncation_reason,omitempty"`
	Errors           []*FetchError          `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	ElapsedMs        int64                  `protobuf:"varint,6,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_sitemap_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sitemap_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_sitemap_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExpandResponse) GetUrls() []*UrlEntry {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ExpandResponse) GetSitemapsFetched() int32 {
	if x != nil {
		return x.SitemapsFetched
	}
	return 0
}

func (x *ExpandResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ExpandResponse) GetTruncationReason() string {
	if x != nil {
		return x.TruncationReason
	}
	return ""
}

func (x *ExpandResponse) GetErrors() []*FetchError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ExpandResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

var File_sitemap_service_proto protoreflect.FileDescriptor

const file_sitemap_service_proto_rawDesc = "" +
	"\n" +
	"\x15sitemap_service.proto\x12\x0esitemap.svc.v1\"c\n" +
	"\x06Limits\x12\x19\n" +
	"\bmax_urls\x18\x01 \x01(\x05R\amaxUrls\x12!\n" +
	"\fmax_sitemaps\x18\x02 \x01(\x05R\vmaxSitemaps\x12\x1b\n" +
	"\tmax_depth\x18\x03 \x01(\x05R\bmaxDepth\"\xb1\x01\n" +
	"\rExpandRequest\x12!\n" +
	"\fsitemap_urls\x18\x01 \x03(\tR\vsitemapUrls\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12.\n" +
	"\x13crawl_delay_seconds\x18\x03 \x01(\x01R\x11crawlDelaySeconds\x12.\n" +
	"\x06limits\x18\x04 \x01(\v2\x16.sitemap.svc.v1.LimitsR\x06limits\"]\n" +
	"\bUrlEntry\x12\x10\n" +
	"\x03loc\x18\x01 \x01(\tR\x03loc\x12\x18\n" +
	"\alastmod\x18\x02 \x01(\tR\alastmod\x12%\n" +
	"\x0esource_sitemap\x18\x03 \x01(\tR\rsourceSitemap\"4\n" +
	"\n" +
	"FetchError\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x87\x02\n" +
	"\x0eExpandResponse\x12,\n" +
	"\x04urls\x18\x01 \x03(\v2\x18.sitemap.svc.v1.UrlEntryR\x04urls\x12)\n" +
	"\x10sitemaps_fetched\x18\x02 \x01(\x05R\x0fsitemapsFetched\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12+\n" +
	"\x11truncation_reason\x18\x04 \x01(\tR\x10truncationReason\x122\n" +
	"\x06errors\x18\x05 \x03(\v2\x1a.sitemap.svc.v1.FetchErrorR\x06errors\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x06 \x01(\x03R\telapsedMs2Y\n" +
	"\x0eSitemapService\x12G\n" +
	"\x06Expand\x12\x1d.sitemap.svc.v1.ExpandRequest\x1a\x1e.sitemap.svc.v1.ExpandResponseB9Z7github.com/accretional/proto-sitemap/proto/pb;sitemappbb\x06proto3"

var (
	file_sitemap_service_proto_rawDescOnce sync.Once
	file_sitemap_service_proto_rawDescData []byte
)

func file_sitemap_service_proto_rawDescGZIP() []byte {
	file_sitemap_service_proto_rawDescOnce.Do(func() {
		file_sitemap_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sitemap_service_proto_rawDesc), len(file_sitemap_service_proto_rawDesc)))
	})
	return file_sitemap_service_proto_rawDescData
}

var file_sitemap_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sitemap_service_proto_goTypes = []any{
	(*Limits)(nil),         // 0: sitemap.svc.v1.Limits
	(*ExpandRequest)(nil),  // 1: sitemap.svc.v1.ExpandRequest
	(*UrlEntry)(nil),       // 2: sitemap.svc.v1.UrlEntry
	(*FetchError)(nil),     // 3: sitemap.svc.v1.FetchError
	(*ExpandResponse)(nil), // 4: sitemap.svc.v1.ExpandResponse
}
var file_sitemap_service_proto_depIdxs = []int32{
	0, // 0: sitemap.svc.v1.ExpandRequest.limits:type_name -> sitemap.svc.v1.Limits
	2, // 1: sitemap.svc.v1.ExpandResponse.urls:type_name -> sitemap.svc.v1.UrlEntry
	3, // 2: sitemap.svc.v1.ExpandResponse.errors:type_name -> sitemap.svc.v1.FetchError
	1, // 3: sitemap.svc.v1.SitemapService.Expand:input_type -> sitemap.svc.v1.ExpandRequest
	4, // 4: sitemap.svc.v1.SitemapService.Expand:output_type -> sitemap.svc.v1.ExpandResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sitemap_service_proto_init() }
func file_sitemap_service_proto_init() {
	if File_sitemap_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sitemap_service_proto_rawDesc), len(file_sitemap_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sitemap_service_proto_goTypes,
		DependencyIndexes: file_sitemap_service_proto_depIdxs,
		MessageInfos:      file_sitemap_service_proto_msgTypes,
	}.Build()
	File_sitemap_service_proto = out.File
	file_sitemap_service_proto_goTypes = nil
	file_sitemap_service_proto_depIdxs = nil
}
