// sitemap_service.proto — the gRPC surface of cmd/sitemap-svc.
//
// AUTHORED, NOT GENERATED, and the only .proto this repo carries.
//
// proto-sitemap otherwise commits no proto by design: the sitemap *format* is
// data (formats/sitemap.ebnf), compiled to a descriptor at runtime by xmile's
// engine (CLAUDE.md, ADR 0001). That still holds — nothing here describes the
// sitemap format. This file describes the SERVICE: what a caller sends to ask
// for a walk, and what comes back. The typed sitemap AST remains compiled from
// the grammar and never appears on the wire.
//
// Per CLAUDE.md's rule about adding a hand-written proto, ./regen.sh
// regenerates the Go bindings; the generated .pb.go files are committed, so an
// ordinary build needs no protoc.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: sitemap_service.proto

package sitemappb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SitemapService_Expand_FullMethodName = "/sitemap.svc.v1.SitemapService/Expand"
)

// SitemapServiceClient is the client API for SitemapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SitemapService walks sitemaps into page URLs.
type SitemapServiceClient interface {
	// Expand walks the given sitemap URLs — following a <sitemapindex> to its
	// children, breadth-first — and returns every page URL it can reach.
	Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error)
}

type sitemapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSitemapServiceClient(cc grpc.ClientConnInterface) SitemapServiceClient {
	return &sitemapServiceClient{cc}
}

func (c *sitemapServiceClient) Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpandResponse)
	err := c.cc.Invoke(ctx, SitemapService_Expand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SitemapServiceServer is the server API for SitemapService service.
// All implementations must embed UnimplementedSitemapServiceServer
// for forward compatibility.
//
// SitemapService walks sitemaps into page URLs.
type SitemapServiceServer interface {
	// Expand walks the given sitemap URLs — following a <sitemapindex> to its
	// children, breadth-first — and returns every page URL it can reach.
	Expand(context.Context, *ExpandRequest) (*ExpandResponse, error)
	mustEmbedUnimplementedSitemapServiceServer()
}

// UnimplementedSitemapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSitemapServiceServer struct{}

func (UnimplementedSitemapServiceServer) Expand(context.Context, *ExpandRequest) (*ExpandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Expand not implemented")
}
func (UnimplementedSitemapServiceServer) mustEmbedUnimplementedSitemapServiceServer() {}
func (UnimplementedSitemapServiceServer) testEmbeddedByValue()                        {}

// UnsafeSitemapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SitemapServiceServer will
// result in compilation errors.
type UnsafeSitemapServiceServer interface {
	mustEmbedUnimplementedSitemapServiceServer()
}

func RegisterSitemapServiceServer(s grpc.ServiceRegistrar, srv SitemapServiceServer) {
	// If the following call panics, it indicates UnimplementedSitemapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SitemapService_ServiceDesc, srv)
}

func _SitemapService_Expand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SitemapServiceServer).Expand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SitemapService_Expand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SitemapServiceServer).Expand(ctx, req.(*ExpandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SitemapService_ServiceDesc is the grpc.ServiceDesc for SitemapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SitemapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sitemap.svc.v1.SitemapService",
	HandlerType: (*SitemapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Expand",
			Handler:    _SitemapService_Expand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sitemap_service.proto",
}
